### ISSUE TITLE
Crash on start of level2

### ISSUE THREAD

**Issue by dborosev** [Codes4Fun/RBDOOM-3-BFG#16] opened 2016-11-22 05:20 UTC
Crashes before beginning level 2.  Either from entering the elevator, or going through the Dev menu straight to level 2.  Goes to main menu, and displays ~ console.

**Comment by duig0** [comment] 2016-11-22 08:49
I can confirm the same when using the Dev menu

**Comment by kickymcassington** [comment] 2016-11-22 08:55
Confirmed happened to me as well.

**Comment by Garfunkel64** [comment] 2016-11-22 10:40
Also having this same problem. Can use Dev to change to different levels, but once the end of the level is reached and the game attempts to load the next map, the game crashes to main menu with the console overlay. Can not currently play due to this bug.

**Comment by Nagorak** [comment] 2016-11-22 14:51
Yeah, this happened to me too.  I got to the start of level 2 and the game crashed.  I reloaded, but was back at following the bot.  The same thing happened again when I loaded the next level, so basically I'm shut down.  

I am using the texture pack, I don't know if that could play a part?

**Comment by dborosev** [comment] 2016-11-22 14:57
I tried it without the texture pack, and still happens, so pretty sure its this mod.

**Comment by Garfunkel64** [comment] 2016-11-22 15:24
I read somewhere (reddit?) someone was able to get past it by running the other .exe that came with it. Try that and let us know. I have to hit the hay. (Graveyard)

**Comment by dborosev** [comment] 2016-11-22 17:34
Which other exe?   The only other one is the non-vr exe isn't it?

**Comment by Garfunkel64** [comment] 2016-11-22 17:47
The fallback .exe.

**Comment by paodin** [comment] 2016-11-22 20:42
Hi,  just tried the alternative exe  as suggested and  I can get down the elevator at the end of level 1  but it then jumps to the console.   everything else works fine.   using version 7 of the mod.  any ideas?

**Comment by Codes4Fun** [comment] 2016-11-22 20:56
I reproduced the issue locally with RBDoom3BFG.exe but using RBDoom3BFG.fallback.exe I can't reproduce it. Make sure you really are running RBDoom3BFG.fallback.exe.

The reference, difference between these two is that one is using OpenAL (has spatial audio) and the fallback one does not.

**Comment by Codes4Fun** [comment] 2016-11-22 21:12
I've updated the build (v7.3) with a new OpenAL32.DLL, this one seems to work around the issue for me:

https://github.com/Codes4Fun/RBDOOM-3-BFG/releases/tag/1.1.0-openvr7

**Comment by baggyg** [comment] 2016-11-22 22:22
Confirmed same behavior on 7.2 main EXE. 7.3 was fine - couldn't replicate.

**Comment by Nagorak** [comment] 2016-11-23 02:20
Seems to be fixed in the new version for me.

**Comment by Codes4Fun** [comment] 2016-11-23 16:04
Thanks for testing this guys! Reopen or open a new issue if this happens again.

**Closed as completed by Codes4Fun** 2016-11-23 16:04 UTC
