### ISSUE TITLE
PDA/Holster Slots

### ISSUE THREAD

**Issue by mamefan** [Codes4Fun/RBDOOM-3-BFG#53] opened 2016-12-10 01:47 UTC
I'm just letting you know that I don't like the slots. I keep trying to turn my flashlight on and end up opening my PDA. Also, the guns in the holster slot aren't in my weapon inventory when clicking, and I prefer clicking the trackpad. Also, the vibrations when touching either side are driving me crazy. I'm going to switch back to the previous version. Thank you for continuing to work on this. The only thing I'd like to see added, if possible, is being able to lean over railings, desks, etc. I know you're already working on that.

**Comment by Codes4Fun** [comment] 2016-12-10 03:05
Out of curiosity is your vr_playerHeightCM set correctly? If the value is lower than your actual height then possibly your arms will hang lower. In the future I will probably make vr_playerHeightCM automatic or as an initial calibration.

I experienced a similar problem and I actually lowered them to be more on the thighs instead of my hips, it is just in documentation I keep referring to them as being on the hips. So that is why I wonder if maybe the issue is the vr_playerHeightCM is not correct.

But I will also see if I can push them lower, tone down the vibration and provide a way to disable them Thanks for the feedback!

I do have working code for leaning but I have not released it yet, there are some other things I am working on at the moment.

**Comment by mamefan** [comment] 2016-12-10 14:53
I haven't ever modified player height, just control type (2), laser sight size, and flashlight time. I'm 5'9".

**Comment by Codes4Fun** [comment] 2016-12-10 17:24
So you are about 4 inches taller than the default height, about 2% difference, doesn't seem like height is a big issue. It could be a combination of the shape and position, maybe they should be further back and I should use rectangles instead of spheres, and it might help if I shrink the holster slot when not in use.

When I implement a calibration screen, I probably will need to ask users to put their hands lower on their sides to get an idea of their reach. It would be useful for building the IK model as well.

**Comment by mamefan** [comment] 2016-12-12 01:47
Thank you for v11 with the leaning over stuff upgrade! Can we get an option to remove the weapon slots? I'd prefer the weapons and PDA the old way.

**Comment by Codes4Fun** [comment] 2016-12-12 01:52
> Thank you for v11 with the leaning over stuff upgrade! Can we get an option to remove the weapon slots? I'd prefer the weapons and PDA the old way.

I'm hoping to get that in the next release, the old way still works, or should be working, if it isn't working let me know.

**Comment by Codes4Fun** [comment] 2016-12-14 22:00
Looks like vr_slotDisable in my last release broke the flashlight. I updated it, and I also added that if you disable slots when the holster is in use that it will also return the holstered weapon.

**Comment by mamefan** [comment] 2016-12-14 22:04
Thank you for vr_slotDisable!

**Comment by Codes4Fun** [comment] 2016-12-14 22:35
> Thank you for vr_slotDisable!

No problem, I pushed out the update as version 12.1 replacing 12.0 on the same page:

https://github.com/Codes4Fun/RBDOOM-3-BFG/releases/tag/1.1.0-openvr12

**Comment by mamefan** [comment] 2016-12-14 23:15
I just tried 12.1, and the flashlight wouldn't stay in my hand. It wasn't in my hand after doing vr_slotDisable 1 but could still be turned on and off.

**Comment by mamefan** [comment] 2016-12-14 23:16
For example, put the controllers down to go to the keyboard, do the command, go back to pickup controllers, and the flashlight stays where the controller was when it was stationary (ground or desk).

**Comment by Wip3ou7** [comment] 2016-12-15 00:01
what exactly is vr_slotDisable 0/1 supposed to do? i thought it turned off the pda on your thigh but it doesnt seem to do anything... i wish i could turn that off, and/or alter its height

**Comment by Codes4Fun** [comment] 2016-12-15 00:23
sorry I messed up the release...

**Comment by Codes4Fun** [comment] 2016-12-15 00:27
okay, now it's updated..

I separate my release builds from my development builds (because sometimes I have stuff left over) and I forgot to sync my release repository before building it :p

**Comment by mamefan** [comment] 2016-12-15 00:33
Wip3ou7, using vr_slotDisable 1 removes the pda and weapon slots, so it goes back to how it was before with no slots.

**Comment by Codes4Fun** [comment] 2016-12-15 00:42
> i thought it turned off the pda on your thigh but it doesnt seem to do anything

It turns off all slots. PDA, holster, next/prev weapon slots. But there is a bug where if you disable it in a live game the PDA will float in mid air (it is no longer attached to you), but the PDA is technically off from the standpoint of slots. The controller will not vibrate and it can't activate the PDA if you click the grip in the "PDA slot".

BUT If you start a game after setting 'vr_slotDisable 1' then the PDA is never spawned and slots are still disabled (no vibration or activation).

It's a minor bug that can be fixed in another release at a later time, my concern is if you accidentally use the holster slot and get pissed and want to disable them, that the holstered weapon doesn't become inaccessible, so I fixed that specific bug as part of my update.

**Comment by Wip3ou7** [comment] 2016-12-15 00:44
holster and next/prev weapon slots? i only ever see the pda floating below me. also ill try restarting the game thanks lol i was looking down after typing it in the console and seeing the pda blow me still so i thought it didnt work rofl

**Comment by Codes4Fun** [comment] 2016-12-15 00:51
> holster and next/prev weapon slots? i only ever see the pda floating below me

I don't have any placeholder artwork, but the holster slot is on the leg opposite the pda, and you can store a weapon there, so you can store the machine gun and hold the plasma gun and quickly swap them back and forth by activating the slot.

The next weapon slot is behind your right shoulder, like reaching into a backpack.

The previous weapon slot is the bottom of your back, like if you were reaching into the bottom of a backpack.

**Comment by Codes4Fun** [comment] 2016-12-15 00:53
Actually you can use "vr_slotDebug 1" to see them drawn with debug lines to get an idea where they are.

**Comment by Wip3ou7** [comment] 2016-12-15 01:21
thanks for the explanation lol i def would not have figured that out

**Comment by Wip3ou7** [comment] 2016-12-15 01:33
hmmm after i restart the flashlight is missing as well :( im using 12.1

**Comment by Codes4Fun** [comment] 2016-12-15 01:37
I'm pretty sure you just need to redownload it.

**Comment by Wip3ou7** [comment] 2016-12-15 01:43
i did redownload it, the zip is 12.1.... as soon as i 'vr_slotDisable 1' the flashlight floats stationary like the pda

**Comment by Wip3ou7** [comment] 2016-12-15 01:48
lol i redownloaded 12.1 again and it works...................... did you stealth 12.2 lol

**Closed as completed** 2016-12-18 23:32 UTC
